update readme examples with correct API, URLs and package-name
huggingface/optimum-quanto pull request #229
Opened 2024-07-04 18:57 UTC by sugatoray

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/optimum-quanto/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you run all tests locally and make sure they pass. `NA`
- [ ] Did you write any new necessary tests? `NA`

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

2024-07-04 19:08 UTC, sugatoray commented
This change is also tied to the fixes proposed in the following PR for Quanto-Blog:

https://github.com/huggingface/blog/pull/2190

2024-07-08 07:02 UTC, dacorvo requested changes
Thank you for this pull-request. The imports had been omitted for the sake of simplicity, but I don't mind adding them (and qint8 was already imported).
You need to use conventional commits in your pull-request, otherwise it cannot be merged.

2024-07-08 07:02 UTC, dacorvo commented on README.md
> +
```suggestion
```

2024-07-17 06:42 UTC, dacorvo commented
Closing as obsoleted by #243

2024-07-17 06:42 UTC, closed without merging